server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    data-username: root
    data-password: admin

jwt:
  tokenHeader: Authorization #请求头
  secret: mySecret #加解密使用的密钥
  expiration: 604800 #超期限时间(60*60*24)
  tokenHead: Bearer #负载头